In [22]:
import json

import pandas as pd
import requests
from pyjstat import pyjstat

In [30]:
postUrl = "https://data.ssb.no/api/v0/en/table/07230/"

In [37]:
apiQuery = {
  "query": [
    {
      "code": "Region",
      "selection": {
        "filter": "item",
        "values": [
          "004"
        ]
      }
    },
    {
      "code": "Boligtype",
      "selection": {
        "filter": "item",
        "values": [
          "00",
          "01",
          "02",
          "03"
        ]
      }
    }
  ],
  "response": {
    "format": "json-stat2"
  }
}

In [38]:
def apiToDataframe(postUrl, query):

	# postUrl PostUrl where you you want the query posted


	res = requests.post(postUrl, json=query)
	# put the result in variable ds. Here you also have some metadata
	ds = pyjstat.Dataset.read(res.text)
	# write resultatet to 2 dataframes
    # first dataframe with text
	df = ds.write('dataframe')
    # next dataframe with codes
	df_id = ds.write('dataframe', naming='id')
    # returner also ds if one need metadata
	return df, df_id, ds

In [39]:
df, df_id, ds = apiToDataframe(postUrl, apiQuery)

In [40]:
df

,region,type of building,contents,year,value
0,Trondheim,Total,Price index for existing dwellings,1992,0.0
1,Trondheim,Total,Price index for existing dwellings,1993,0.0
2,Trondheim,Total,Price index for existing dwellings,1994,0.0
3,Trondheim,Total,Price index for existing dwellings,1995,0.0
4,Trondheim,Total,Price index for existing dwellings,1996,0.0
...,...,...,...,...,...
119,Trondheim,Multi-dwelling,Price index for existing dwellings,2018,108.6
120,Trondheim,Multi-dwelling,Price index for existing dwellings,2019,109.7
121,Trondheim,Multi-dwelling,Price index for existing dwellings,2020,112.7
122,Trondheim,Multi-dwelling,Price index for existing dwellings,2021,124.1
123,Trondheim,Multi-dwelling,Price index for existing dwellings,2022,130.1